### ISSUE TITLE
Paint Editor doesn’t work on mobile

### ISSUE THREAD

**Issue by ghost** [GrooveProgramming/Groove-Paint#4]
**Description of the bug**
When you go into the paint editor, it is expected to work on mobile. It should work on mobile.

**To Reproduce**

1. Go to the paint editor on mobile.
2. Click mouse.
3. Try moving the mobile mouse.
4. See that it doesn’t draw.

**Expected behavior**
You should be able to draw lines, not just dots.

**Platform Information**
 - Device: iPad (7th generation)
 - OS: iOS
 - Browser Safari
 - Version 13

**Additional context**
The code looked fine to me. I’m not sure what the problem is.

**Comment by Mapletron** [comment]
Yep, I'm also experiencing the same issue.

**Comment by ghost** [comment]
> Yep, I'm also experiencing the same issue.

We really need to work on the pe. :/

**Comment by ghost** [comment]
@B294 have a look at https://stackoverflow.com/questions/22015908/onclick-not-working-on-mobile-touch

**Comment by ghost** [comment]
@JimmyRooster Thanks. Closed as resolved.
